export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
        extend: {
          "colors": {
            "surface-variant": "#2f3542",
            "on-tertiary": "#3c0091",
            "inverse-primary": "#9d4300",
            "on-secondary-fixed": "#001f26",
            "secondary-fixed-dim": "#4cd7f6",
            "on-secondary-fixed-variant": "#004e5c",
            "surface-container-high": "#242a36",
            "tertiary-container": "#a985ff",
            "error": "#ffb4ab",
            "on-error-container": "#ffdad6",
            "primary": "#ffb690",
            "primary-fixed": "#ffdbca",
            "on-primary-fixed": "#341100",
            "on-secondary-container": "#00424e",
            "on-surface-variant": "#e0c0b1",
            "surface-container": "#1a202c",
            "secondary-container": "#03b5d3",
            "surface-bright": "#343946",
            "outline-variant": "#584237",
            "secondary-fixed": "#acedff",
            "primary-fixed-dim": "#ffb690",
            "error-container": "#93000a",
            "secondary": "#4cd7f6",
            "surface-dim": "#0e131f",
            "primary-container": "#f97316",
            "surface-container-low": "#161c28",
            "on-tertiary-fixed": "#23005c",
            "on-tertiary-container": "#3e0096",
            "on-primary": "#552100",
            "on-secondary": "#003640",
            "tertiary-fixed": "#e9ddff",
            "on-error": "#690005",
            "on-primary-fixed-variant": "#783200",
            "surface-tint": "#ffb690",
            "surface-container-highest": "#2f3542",
            "outline": "#a78b7d",
            "on-background": "#dde2f3",
            "surface": "#0e131f",
            "tertiary-fixed-dim": "#d0bcff",
            "on-tertiary-fixed-variant": "#5516be",
            "inverse-surface": "#dde2f3",
            "surface-container-lowest": "#080e1a",
            "background": "#0e131f",
            "tertiary": "#d0bcff",
            "inverse-on-surface": "#2b303d",
            "on-primary-container": "#582200",
            "on-surface": "#dde2f3"
          },
          "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
          },
          "spacing": {
            "space-xs": "0.25rem",
            "margin": "3rem",
            "space-xl": "2.5rem",
            "space-md": "1rem",
            "space-lg": "1.5rem",
            "margin-mobile": "1rem",
            "gutter-mobile": "0.75rem",
            "gutter": "1.5rem",
            "space-sm": "0.5rem"
          },
          "fontFamily": {
            "body-md": ["Inter"],
            "body-lg": ["Inter"],
            "headline-lg-mobile": ["Space Grotesk"],
            "headline-xl-mobile": ["Space Grotesk"],
            "headline-xl": ["Space Grotesk"],
            "label-lg": ["JetBrains Mono"],
            "headline-lg": ["Space Grotesk"],
            "headline-md": ["Space Grotesk"],
            "body-sm": ["Inter"],
            "label-md": ["JetBrains Mono"],
            "label-sm": ["JetBrains Mono"],
            "headline-sm": ["Space Grotesk"]
          },
          "fontSize": {
            "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
            "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
            "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "headline-xl-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
            "headline-xl": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
            "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.04em", "fontWeight": "500" }],
            "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
            "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
            "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "500" }],
            "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.12em", "fontWeight": "500" }],
            "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "500" }]
          }
        }
      }
};
