import { Link } from 'react-router-dom';
import { lessons, modules } from '../data/mockData.js';
import { useCalphy, lessonProgress } from '../appContext.js';
import { Icon, Progress } from '../components.jsx';

export default function Dashboard() {
  const context = useCalphy(); const { state } = context; const progress = lessonProgress(context);
  const next = lessons.find((lesson) => !state.completedLessonIds.includes(lesson.id)) ?? lessons[0];
  return <div className="page-stack">
    <section className="hero panel"><div className="hero-copy"><p className="eyebrow">CALPHY · HEAT & TEMPERATURE LAB</p><h1>Understand heat.<br/><span>Explore temperature.</span></h1><p className="lead">Build a clear picture of thermal physics through short lessons, worked examples, and an interactive particle simulator.</p><div className="button-row"><Link className="button button-dark" to={`/lessons/${next.id}`}><Icon>play_arrow</Icon> {state.completedLessonIds.length ? 'Continue learning' : 'Start learning'}</Link><Link className="button button-light" to="/simulator"><Icon>device_thermostat</Icon> Explore simulator</Link></div></div><div className="hero-visual" aria-label="Illustration of particle motion at different temperatures"><div className="thermometer"><div className="thermometer-fill"/><span>°C</span></div><div className="particle-field">{Array.from({length: 18}, (_, i) => <i key={i} style={{'--i': i}}/>)}</div><p>Particle motion responds to temperature</p></div></section>
    <section className="metric-grid"><article className="metric panel"><span>Lessons completed</span><strong>{state.completedLessonIds.length}<small> / {lessons.length}</small></strong><Progress value={progress}/></article><article className="metric panel"><span>Learning streak</span><strong>{state.profile.streak}<small> days</small></strong><p className="muted">A little practice adds up.</p></article><article className="metric panel"><span>Current temperature</span><strong>{state.temperature}<small> °C</small></strong><Link to="/simulator">Open the simulator <Icon>arrow_forward</Icon></Link></article></section>
    <section className="section-block"><div className="section-heading"><div><p className="eyebrow">PICK UP WHERE YOU LEFT OFF</p><h2>{next.title}</h2><p className="muted">{next.summary}</p></div><Link className="text-link" to={`/lessons/${next.id}`}>Continue <Icon>arrow_forward</Icon></Link></div></section>
    <section className="section-block"><div className="section-heading"><div><p className="eyebrow">LEARNING PATH</p><h2>Explore thermal physics</h2></div><Link className="text-link" to="/lessons">All lessons <Icon>arrow_forward</Icon></Link></div><div className="module-grid">{modules.map((module, i) => <Link className="module-card panel" key={module.id} to={`/lessons?topic=${module.topic}`}><span className="module-number">0{i + 1}</span><p className="eyebrow">{module.subtitle}</p><h3>{module.title}</h3><p className="muted">{module.description}</p><span className="text-link">{module.lessonIds.length} lessons <Icon>arrow_forward</Icon></span></Link>)}</div></section>
    <section className="callout panel"><div><p className="eyebrow">TRY A QUICK EXPERIMENT</p><h2>What changes when particles warm up?</h2><p className="muted">Adjust the temperature and observe a simple particle-motion model.</p></div><Link className="button button-dark" to="/simulator">Launch simulator <Icon>arrow_forward</Icon></Link></section>
  </div>;
}
